# Generated by Django 5.0.2 on 2024-02-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='type_material',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text'), ('pdf', 'PDF')]),
        ),
    ]
