# Generated by Django 5.0.2 on 2024-02-25 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
